# Generated by Django 5.0.7 on 2024-08-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_userwifiplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiplan',
            name='data_limit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
